# Generated by Django 6.0.4 on 2026-05-03 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200)),
                ('type_name', models.CharField(max_length=200)),
                ('ram', models.IntegerField()),
                ('weight', models.FloatField()),
                ('cpu_brand', models.CharField(max_length=200)),
                ('gpu_brand', models.CharField(max_length=200)),
                ('os', models.CharField(max_length=200)),
                ('predicted_price', models.IntegerField()),
            ],
        ),
    ]
